### PR TITLE
Add GitHub action to automatically build a new wgt package each time a change is pushed.

### PR DESCRIPTION
**Pull request by gardner**
This PR adds a docker-based build workflow to build and publish the `Jellyfin.wgt` as a build artefact.

### CODE REVIEW

**Comment by bdovaz** [comment]
@dmitrylyzo any news on this PR?

**Comment by ilteoood** [comment]
@dmitrylyzo can this be merged?

**Comment by dmitrylyzo** [comment]
I'm far from being a CI expert, but here are some thoughts:
- It would be better to use the current (_w/o redownloading_) jellyfin-tizen source so that the docker can be used to build the modified app. Maybe mount as volume?
_At the same time, the developer has Tizen Studio and other stuff installed._ :man_shrugging:
_And what about a custom jellyfin-web?_ :thinking: 

- The previous CI attempt (Asure) was suspended due to reinstalling Tizen Studio every time CI was started. Does GHA have caching ability?

- At some point, the app should be bound to a specific jellyfin-web version. _The current master branch is broken due to the transition to React._ In the previous attempt (Asure) this was done using `package.json` - this removes the separate "build the web" step, but it cannot be skipped for using the custom web, iirc. _I wish jellyfin-web be an actual node module._ :crossed_fingers: 
The current PR proposes using environment variables, right?
I guess we need stable and unstable builds.

- Currently I don't know if Anthony will build the Tizen app manually (without docker), so I am not sure what to do with the actual (publishing) certs.

**Comment by vinicentus** [comment]
Just wanted to add that there exist a working implementation in [jeppevinkel/jellyfin-tizen-builds](https://github.com/jeppevinkel/jellyfin-tizen-builds)

**Pull request closed without merging**
