### PR TITLE
Added MediaPlayPause listener

### PR DESCRIPTION
**Pull request by vov4uk**
Play/Pause button will work

### CODE REVIEW

**Comment by dmitrylyzo** [comment]
IIRC, when `MediaPlayPause` is enabled, the OSD hint (with 5 virtual buttons: FastForward, Rewind, Previous track, Next track, Play/Pause) for Smart Remote doesn't work.

**Comment by vov4uk** [comment]
I'm not familiar with Tizen development - but after this fix, my UE49KU6470 works correctly with my remote control

**Comment by dmitrylyzo** [comment]
What remote control is used?

|Remote Control|Samsung Smart Remote|
|---|---|
|  |  |

According to the UE49KU6470 manual, its Smart Remote should show on-screen playback control when pressing Play/Pause like other models.

Samsung may require this button to work as Play/Pause to pass certification, but this is a loss of functionality, imo. At the same time, on-screen control functionality exists on the video OSD bottom panel. :man_shrugging:

**Comment by vov4uk** [comment]
I use "Samsung Smart Remote". If you have any concerns, feel free to cancel the pull request.

**Comment by TomasMonkevic** [comment]
I can confirm that the play pause button doesn't work on the new Samsung Smart Remote. Only the middle press in the circle works

**Comment by mullerdavid** [comment]
I agree it's a loss of functionality, but personally I prefer the plain play/pause functionality. The best of both would be to implement some kind of option for it that can be set in the app.

**Comment by dmitrylyzo** [comment]
Superseded by #184

**Pull request closed without merging**
